### PR TITLE
Fix monoid examples

### LINKED ISSUE #26: The use of Monoid for Global values is a bit strange
Currently, apecs uses the `mempty` member of `Monoid` to provide a default for global values. This makes sense initially: it's the standard Haskell way to represent the "default" value of something.

However, problems come when we start defining other global components. I often have global components which do not sensibly fit the `Semigroup` or `Monoid` laws. For example, given something like this:

```haskell
newtype Score = Score { getScore :: Int }
```

There's really no sensible way for me to "monoidally combine" scores, because they're not intended to have that kind of structure. I could always leave the instances blank except for `mempty`, or write rule-breaking instances, but that might be surprising to other users.

As such, I propose a new typeclass:

```haskell

class ApecsGlobal a where
    apecsDefault :: a
```

We could then use `apecsDefault` instead of `mempty` where needed. We could even define this:

```haskell
instance (Monoid a) => ApecsGlobal a where
    apecsDefault = mempty
``` 

This would provide backwards-compatibility.

### PR DESCRIPTION
**Pull request by AnthonySuper**
This basically fixes #26 by giving examples for how to make your `Global` values proper `Monoid`s.

I considered adding in a `gmappend` in this PR but figured that should probably be in its own.

### CODE REVIEW

**Comment by jonascarpay** [comment]
Would you mind deriving a Num instance, so we can just say `mappend = (+)` and `mempty = 0`?

**Comment by AnthonySuper** [comment]
Pushed new commits but the build is still failing (oh no)

**Comment by jonascarpay** [comment]
Yeah the `Semigroup` business can be a pain in the ass. Maybe we should just drop GHC 8.2 support.

**Comment by jonascarpay** [comment]
I've pulled & rebased this on the new `monoid-docs` branch. I'll fix the build errors and merge from there.

**Pull request closed without merging**
