### PR TITLE
Bump stack resolvers

### PR DESCRIPTION
**Pull request by dpwiz**
Add LTS-21, with GHC-9.4

### CODE REVIEW

**Comment by jonascarpay** [comment]
Thanks! Feel free to merge. I think we can safely make the nightlies optional.

**Comment by dpwiz** [comment]
Hm.. Something is stuck. Waiting for a phantom build?

**Comment by dpwiz** [comment]
@jonascarpay Looks like you have to force it past the missing check.

**Comment by jonascarpay** [comment]
Oh, you removed the nightly build but it's still marked as required in the branch settings. GHA isn't clever enough to figure out that it's gone, so it stays pending.

**Pull request merged**
